ci/steps.yml
Pro:
1 step instead of 2 for all platforms. Very consistent. The steps file is getting a bit bloated.
Con:
People don't usually use Powershell as their shell on macOS and Linux. The fact it is preinstalled on all Azure Pipeline runners on all the platforms is quite unusual. 
I don't know what decision to make. It's something I noticed.
=> Simplify steps by using powershell on both platforms to install built package.

azure-pipelines.yml, generate_azure_pipelines_yml.py
Keeps down the pipeline.yml diff noise
=> Use ordered dictionaries to make generated AP yaml output consistent between Python 3.6 and 3.7

azure-pipelines.yml, generate_azure_pipelines_yml.py
AQT is for CI/CD. Users might develop Android Apps on Mac/Windows but
they are far more likely to choose the most available platform for CI/CD
of their apps: Linux.
=> Scale testing of Android Targets to just Linux

requirements.txt
The ruamel.yaml library was used for the original matrix generation script. It is not required inside aqtinstall's development/ci/cd environment.
=> No need for yaml modification library

aqt/__init__.py, aqt/cli.py, aqt/installer.py
- combination with thread pool for downloading and
process pool for extraction.
- Performance improvement to resolve #86 
=> Use concurrent.futures for concurrency with thread and process

aqt/installer.py, setup.cfg
WIP for:
- This should happen before releasing aqtinstall but isn't related to this PR...
- Well, other than this PR failing so, sure, depends on preference, but it needs to happen regardless
=> No more os.chdir()

aqt/helper.py, aqt/installer.py, tests/test_helper.py
Also fix a bug not accept a header context-type when
got charset parameter such as
application/meta4+xml; charset=utf-8
=> Refactoring altlink helper

setup.cfg
Update dependency to v0.9.0 and later.
Fix for #149
=> Fix installation of Qt5.7 which use LZMA1+BCJ

.github/workflows/test-install-qt.yml, .travis.yml, azure-pipelines.yml, docs/cli.rst, setup.cfg, tox.ini
- Avoid py7zr v0.10.0
- GHA: test against Qt LTS versions
- GHA: Add test for Qt 6.0.0
=> update py7zr dependent version and  test target versions

aqt/archives.py, tests/data/windows-5152-src-doc-example-update.xml, tests/test_doc_archives.py
Add filter on doc and example packages when option "all_extra" is enabled.
Add test.
=> When we used "-m all" to download doc or examples, Qt sources are also downloaded

aqt/installer.py
- Close multiprocessing.pool to release resource
- Fixed #218
=> Fix resource leak

README.rst
I believe it was meant to be `--outputdir /opt/Qt`, because having it installed in /opt/5.12.0 with no mention of Qt would be confusing.
=> README - fix example for installing into /opt

.github/workflows/check.yml
This is meant to allow `tox` to run in Github Actions, every time a push or PR event occurs. In the discussion for #235, @miurahr mentioned that `tox` doesn't appear to run in CI, so I looked up the directions at https://docs.github.com/en/actions/guides/building-and-testing-python#running-tests-with-tox, and copied a few things. `tox` is now running properly in GH Actions, using Python 3.6 and 3.8.
~~Please see https://github.com/ddalcino/aqtinstall/actions/runs/838159498 for a successful run; I don't know why the link isn't showing up under **"Checks"** below.~~ A successful run should appear in the **"Checks"** below.
=> Fix tox check in GH Actions

aqt/updater.py
any necessary padding.
This also fixes the assertion regarding the length of the new path.
This is an additional required fix for #256.  The need for this additional fix was pointed out in #256 by @ddalcino.
Again, please check my python.  The intent is that every patch insertion shall be exactly 256 bytes consisting of 
1) the key
2) the new path
3) zero padding of at least 1 byte
It's not clear to me that this fixed length string needs to be null terminated, but it might, and it the reduction of the maximum new path length by 1 byte seems an insignificant concession.
I believe python assertions only run with __debug__ is true, which only happens when optimization is not requested. https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
Therefore we may want to further …
=> make sure binfile patches are a full 256 bytes, including

ci/generate_azure_pipelines_matrices.py, ci/steps.yml
This adds two build jobs to the azure pipeline: one that tests a really short output directory, and one for a really long output directory.
This also directly tests the values `qt_prfxpath`, `qt_epfxpath`, and `qt_hpfxpath` in the qmake binary, in the two new build jobs (perhaps this check should be extended to all the build jobs?)
This also hides `<qt_version>/<arch>/bin/qt.conf` in the two new build jobs, to verify that the qmake binary has been patched properly.
This also turns on `xtrace` in `ci/steps.yml`; this made it a lot easier for me to debug the terminal output in the Azure Pipelines jobs. This change probably belongs in a separate PR; please let me know if you'd like me to split this up.
=> Add test and control for patched qmake

ci/generate_azure_pipelines_matrices.py
to reduce CI failed with timeout
=> CI: remove berkley.edu from mirrors test site

README.rst
Recommend  3.8 and 3.9 from 3.7 because there are frequently tested one.
=> README: Change recommended python version

aqt/helper.py
These characters caused Black to crash on my PC. I believe that these characters were committed by mistake; if I am wrong, please close this PR.
=> Remove odd unicode characters from Settings docstring

aqt/updater.py, ci/generate_azure_pipelines_matrices.py
Use `macos` other than `clang_64` for Qt6.2.0 and later on mac/desktop(#288)
=> Change updater target path for Qt 6.2.0 for mac

tests/test_connection.py
The test test_cli_unknown_version, in `tests/test_connection.py`, is never run in CI because it is marked as requiring remote data. When I run `pytest` locally, this test always fails because the version string "5.12" cannot be parsed into a valid `semantic_version.Version` object. This change modifies that version string to "5.16.0", so that it will make a valid Version object that is an invalid version of Qt.
This also modifies the assertion code in test_cli_unknown_version. On my machine, the new logger prints directly to `stderr` and not `stdout` when run via `pytest`, and the `aqt - WARNING` and `aqt - ERROR` prefixes are omitted. The new assertion code uses a regex to pick out the required parts of the output and ignore anything that might not show up.
This change also accounts for …
=> Fix `test_cli_unknown_version`

aqt/installer.py, tests/test_cli.py
Currently, if a user uses `aqt install 5.12 mac desktop`, `semantic_version.Version` will raise a `ValueError` because `5.12` is missing a patch number. This change catches that exception and emits an error message that asks the user to fix that problem.
=> Add error messages when user inputs an invalid semantic version

aqt/archives.py, aqt/installer.py
This removes the `exit(1)` call from the helper function `Cli._validate_version_str`, and makes that function return `True` or `False` instead. This puts the responsibilities of writing error messages and calling `exit` on the caller.
This change allows `Cli.run_list` to call `Cli._validate_version_str`, the same way that `run_install` and `run_src_doc_examples` do.
As a side effect, this allows `tests/test_cli.test_cli_invalid_version()` to pass, as discussed in my comment on #299.
This solution allows the test to pass, and I think it's a better solution than simply changing the test.
=> Validate version strings more consistently

aqt/archives.py
This change prevents an AttributeError from being raised when `ToolArchive.__str__()` is called.
Neither `ToolArchives` nor the parent class `QtArchives` contains the data member `version_str`, yet it is referenced in the `__str__` method. This change replaces it with the correct data member, `QtArchives.version`.
=> Fix `ToolArchives.__str__()`

aqt/archives.py, aqt/helper.py, aqt/installer.py, ci/steps.yml, tests/data/mac-desktop-tools_cmake-expect.json, tests/data/mac-desktop-tools_ifw-expect.json, tests/data/mac-desktop-tools_qtcreator-expect.json, tests/test_helper.py, tests/test_list.py
This adds the ability to list tool module names alongside some extra metadata, including version, release date, display name, and description. Here's some sample output:
```
$ python -m aqt list tools windows desktop --tool-long tools_conan
Tool Variant Name           Version         Release Date     Display Name              Description         
============================================================================================================
qt.tools.conan         1.33-202102101246     2021-02-10     Conan 1.33          Conan command line tool 1.33
qt.tools.conan.cmake   0.16.0-202102101246   2021-02-10     Conan conan.cmake   Conan conan.cmake (0.16.0)
```
This kind of output is really helpful for me personally, since I'm trying to work on `aqt tool`, and that requires …
=> List tool versions

aqt/metadata.py
Currently, the following two commands fail with an HTTP 404 when they shouldn't:
```bash
aqt list qt5 windows desktop --modules 5.9.0
aqt list qt5 windows desktop --arch 5.9.0
```
This happens because ListCommand is looking for an xml file at `<base>/<host>/<target>/qt5_590/Updates.xml`; that file doesn't exist because it's actually at `<base>/<host>/<target>/qt5_59/Updates.xml`. So far, this is the only exception like this.
This change accounts for this exception.
=> Fix failure of requests for Qt 5.9.0

aqt/metadata.py, tests/test_list.py
In the current implementation, if a user runs `aqt list qt6 windows android --modules 6.2.0`, without an extension, aqt prints this:
```
No modules available for this request.
Please use 'aqt qt6 windows android' to show versions of Qt available
```
This happens because all the Qt6 Android modules require an extension for the processor architecture. The current error message does nothing to indicate what the problem is. The user's request seems perfectly reasonable
This change adds a function that checks for obvious misuses and omissions of the `--extension` flag, according to these rules:
1. On Qt6 for Android, an extension for Android processor architecture ("x86_64", "x86", "armv7", "arm64_v8a") is required.
2. On any platform other than Android, or on Qt5, the extensions for Android …
=> Extension validation in ListCommand

aqt/metadata.py, tests/test_list.py
This adds a function to Versions that returns a flattened list of Version objects. This is a spinoff from #318 that I needed for that feature, but I think it's outside the scope of that PR.
This also adds test coverage for the whole Versions class.
=> Add `aqt.metadata.Versions.flattened()`

aqt/logging.ini, aqt/metadata.py
This follows the convention set out by the rest of the project, where the loggers are all named after the files in which they are used.
=> Rename `aqt.list` logger to `aqt.metadata`

aqt/metadata.py, tests/test_list.py
This PR splits `aqt.metadata.suggested_follow_up` into:
1. a function that returns a list of strings, and
2. a function that formats and prints those strings
This PR also adds test code for both functions.
Here is an example of what the formatter prints:
```
==============================Suggested follow-up:==============================
* Please use 'aqt list tools mac desktop --extensions <QT_VERSION>' to list valid extensions.
* Please use 'aqt list tools mac desktop' to check what tools are available.
```
=> Refactor `suggested_follow_up`

aqt/metadata.py, tests/data/windows-desktop-tools_vcredist-expect.json, tests/data/windows-desktop-tools_vcredist-update.xml, tests/test_list.py
This adds eleven tests to `tests/test_list.py`, and increases test coverage for `metadata.py` from 78% to 94%.
There's still room for improvement here. I haven't made progress with some of the tests for `metadata.show_list` because of some issues I'm having with caplog and pytest; see https://github.com/miurahr/aqtinstall/pull/325#discussion_r671942997.
=> Improve test coverage for `aqt/metadata.py`

MANIFEST.in, README.rst, aqt/archives.py, aqt/installer.py, ci/steps.yml, docs/cli.rst
Improve tool command; user can do such as follows;
- `aqt tool windows desktop tools_openssl_x64`
- `aqt tool windows android tools_qt3dstudio_runtime_240`
- `aqt tool windows desktop tools_conan`
- `aqt tool windows desktop tools_vcredist`
- `aqt tool linux desktop tools_ifw`
- `aqt tool mac desktop  tools_ninja`
Implement #282 and fix #233
=> Allow tool sub-command to specify tool_name without version

.github/workflows/check-combinations.yml, aqt/logging.ini, ci/generate_combinations.py
This adds a script called `generate_combinations.py` that:
1. Runs ListCommand to generate a dictionary that approximates the contents of `combinations.json`. This step takes ~2 minutes to run on my machine, so I used `tqdm` to give some indication of progress.
2. Pretty-prints the dictionary to the console, in a way that mimics the formatting of `combinations.json`
3. Prints a detailed comparison of the program output with the actual `combinations.json`.
~~This script makes no attempt to check `new_archive`, since that is something that ListCommand cannot do.~~
~~**Edit:** I added a function to metadata.py that reads 'new_archive', so this tool can now reproduce the whole `combinations.json` file.~~
**Edit:** The 'new_archive' data is now inherited from the previous `combinations.json` …
=> Add GH Action to autogenerate `combinations.json`

.github/workflows/check-combinations.yml
The URL printed as part of the PR message for #344 should point to the workflow run that generated the action. Unfortunately, I got the syntax wrong, and that link in that page returns HTTP 404.
I think this should fix the problem.
=> Fix URL in auto-generated pull request

setup.cfg, tests/test_install.py, tests/test_list.py
This change adds unit tests for the `aqt install` and `aqt install-qt` commands, and establishes a pattern that can be extended for more tests. This is intended to make it easier to increase test coverage of parts of the codebase that are not yet covered by tests.
This uses the `pytest-socket` library to ensure that the tests do not use any network IO. It also mocks `multiprocessing.get_context` to prevent multiprocessing. This is necessary because multiprocessing spawns child processes that have not been monkey-patched, which would break the test.
These tests use py7zr to create mock 7z archives, which are installed and patched in a temporary directory. The tests check the content of the patched files and any output to stderr.
I think that this will increase the code coverage of this …
=> Add 'tests/test_install.py'

docs/cli.rst
This adds 'List-*' and 'Install-*' subheadings, with the corresponding subcommands as children of those items. It also adds a 'Common Options' section.
Fix #339.
=> Organize cli.rst into categories

aqt/archives.py, aqt/updater.py, ci/generate_azure_pipelines_matrices.py, tests/test_install.py
I think this should fix #363. It adds:
1. unit tests for installing Qt 5.9,
2. an extra Azure Pipeline build job for Qt 5.9.0/Windows/Desktop/MSVC2017_64, and
3. the function `QtArchives._version_str()`, which contains all the logic for deciding how to turn a Qt Semantic Version into a string, for use in a url or an Updates.xml PackageUpdate name.
**Edit:** The BuildJob failed; looks like it didn't update `qconfig.pri` properly. This is not ready to merge yet.
Apperently, Qt 5.9.0 installs to a directory called "5.9" and not "5.9.0", so the patching step fails.
=> Fix Qt 5.9.0 installation

aqt/installer.py
The combination-checking code that this PR removes is obsolete. All of these checks are done better by the `combinations.json` file, which is now kept current by a bot running in CI.
Fix #369
=> Remove incorrect combinations checks

aqt/archives.py, tests/data/mac-desktop-tools_qtcreator-expect.json, tests/test_archives.py
This implements the other half of #374, so that `aqt install-tool` should fail if you tell it to install a tool variant that doesn't exist.
=> Fail installation on missing tool variants

.github/workflows/check-combinations.yml
See #386 .
Q: Why update so early?
A: The ["check combinations.json" step](https://github.com/miurahr/aqtinstall/blob/c094930a489795cedb11124fff89511825eb31d5/.github/workflows/check-combinations.yml#L34-L35) will update the "/aqt/combinations.json" file. If I check out the "update-combinations" branch after this step, git will complain that our *local changes would be overwritten by merge*. Also, I think it's not a bad thing to put git stuff together.
Q: Why use `branchtomerge: "origin/master"` , not `branchtomerge: "master"` ?
A: At that time, there was no "master" branch locally.
/cc @ddalcino
=> In the "check combinations.json" workflow, update the "update-combinations" branch as soon as possible to avoid merge conflicts

aqt/archives.py, aqt/exceptions.py, aqt/helper.py, aqt/installer.py, aqt/metadata.py, aqt/settings.ini, aqt/updater.py, tests/test_archives.py, tests/test_cli.py, tests/test_connection.py, tests/test_helper.py, tests/test_install.py, tests/test_list.py, tests/test_updater.py
This migrates the error handling strategy of `aqt/installer.py` from "print error message, then exit(1)" towards consistently raising and catching exceptions. See #381 for more details.
This also adds an option to `settings.ini` that allows you to turn stack traces on and off during error reporting. This behavior could probably be triggered by a command line option, but I didn't think of that.
Fix #381.
**Note**: I intend to keep this on WIP until I have test coverage for every instance of `raise AqtException` that I have altered or added.
**Edit**: There are now at least 11 instances of `raise AqtException` that I have altered or added:
=> Improve error handling

aqt/archives.py, aqt/installer.py, aqt/metadata.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml, docs/cli.rst, docs/getting_started.rst, tests/test_cli.py, tests/test_list.py
This implements the last item in #306: installing Qt by specifying a SimpleSpec rather than a Version.
This makes a small but important change to the planned interface:
```diff
aqt install-qt mac desktop 5.15.2                   # installs Qt 5.15.2
- aqt install-qt mac desktop --spec ">1,<6"         # installs Qt 5.15.2 by SimpleSpec
+ aqt install-qt mac desktop ">1,<6"                # installs Qt 5.15.2 by SimpleSpec
```
I felt that it was easier to implement the feature this way, as well as being easier to type and explain in the documentation. If you disagree with this change, please let me know and I'll figure out how to implement the interface as planned.
Fix #306
=> Specify version by SimpleSpec

docs/cli.rst
Test result:
```console
$ aqt version
aqtinstall(aqt) v2.0.0rc4 on Python 3.8.10 [CPython GCC 9.4.0]
$ aqt list-tool windows desktop tools_conan
qt.tools.conan
qt.tools.conan.cmake
$ aqt list-tool windows desktop tools_conan -l
Tool Variant Name           Version         Release Date     Display Name              Description         
============================================================================================================
qt.tools.conan         1.33-202102101246     2021-02-10     Conan 1.33          Conan command line tool 1.33
qt.tools.conan.cmake   0.16.0-202102101246   2021-02-10     Conan conan.cmake   Conan conan.cmake (0.16.0)  
```
=> docs(cli): correct the parameter of "list-tool" in an example

docs/cli.rst
This is meant to allow CI builds to run successfully when the mirror link in `cli.rst` is broken. It accomplishes this by changing the link into an html 'code' tag. The link is not meant to be clicked on; it is meant to be typed as a command line argument. This change makes the intention more explicit.
Additionally, this replaces the url with a working URL, in case anyone is tempted to copy it into the terminal.
=> Fix broken mirror link in cli.rst 

aqt/archives.py, aqt/installer.py, aqt/metadata.py, tests/test_archives.py, tests/test_connection.py, tests/test_install.py
This adds error messages that suggest using `aqt list-*` when a user attempts to install:
1. Versions of Qt that don't exist
2. Modules that don't exist
3. Tools that don't exist
4. Tool variants that don't exist
See changes to `tests/test_install.py` for examples of the expected error messages.
The idea here is that the user will be encouraged to use `aqt list-qt` and `aqt list-tool` when one of these errors occur, instead of trying to figure out why a 404 occurred, and trying to debug `aqt` to figure out what went wrong.
There's one thing that I didn't do that could potentially improve this: We could automatically run the suggested `aqt list-*` command and print "These are the available values for the parameter you got wrong: [...]" in the error message, instead of asking the user to …
=> Add helpful error messages when modules/tools/Qt version does not exist

aqt/archives.py, aqt/installer.py, tests/test_archives.py, tests/test_cli.py
Fix #413.
This fix will correctly map the legacy v1.* commands to the new v2.* commands, with backwards-compatible syntax.
Where necessary, the new commands should be modified to reproduce the legacy behavior when run in legacy mode. Right now, I think the only place we need to do this is `aqt tool`, where the legacy command would only install a tool if it matches the supplied version.
~~Right now, all I have are tests; implementation will follow.~~
**Edit**: forgot to implement legacy `aqt tool` behavior
**Edit**: implemented legacy `aqt tool` behavior that fails to install the tool when the version numbers don't match. Also re-implemented legacy bug that prevents installation of tools that don't have a valid semantic version. 💩 Hopefully, users who experience this bug will be motivated …
=> Fix legacy commands

aqt/exceptions.py, aqt/helper.py, aqt/installer.py, aqt/settings.ini, docs/configuration.rst, tests/test_helper.py
This allows downloads of archives to be retried when checksum errors occur, as discussed in https://github.com/miurahr/aqtinstall/issues/416#issuecomment-932472110. Even after I [turned off my VPN](https://github.com/miurahr/aqtinstall/issues/416#issuecomment-933031438), I am still getting so many checksum errors that it takes me several tries before I can successfully install Qt. If any of our users are having similar trouble, I'm sure that they are extremely frustrated with `aqt`, and I think that this change could be helpful for them.
I'm not certain that this is the best implementation of this feature; please see my notes below.
=> Allow retry of download on checksum error

aqt/installer.py, tests/conftest.py, tests/test_cli.py, tests/test_connection.py, tests/test_helper.py, tests/test_install.py, tests/test_updater.py
In an earlier PR, I added calls to `disable_socket()` from `pytest_socket` where I thought they were needed to prevent some tests from accessing the network, in case they weren't monkeypatched properly. Today, I discovered that `disable_socket()` disables sockets globally for all tests, which means that the tests that use remote data cannot run if they are executed after another test calls `disable_socket()`.
This change calls `disable_socket()` once from `conftest.py`, so that no tests are allowed to use network data unless they are marked as OK to use the network, with `@pytest.mark.enable_socket`. See example of usage in `tests/test_connection.py`.
See [pytest_socket docs](https://github.com/miketheman/pytest-socket).
=> Fix usage of `disable_socket`

aqt/installer.py, docs/cli.rst, tests/test_install.py
This is intended to address #436, but it probably does not fix it outright.
This adds a suggestion to the `OutOfMemory` error message that the user can try an alternate 7z extractor program with the `--external` flag, with a link to the documentation for that flag. This also adds some hints on where to acquire an external 7z extractor.
I am concerned that telling users where to obtain an external 7z extractor might be a little excessive. I think it's very unlikely that a developer using aqtinstall doesn't already have such tools installed. It is probably better to be neutral about which tool users should use, and not promote any one 7zip extractor tool. However, I would prefer to err on the side of being "too helpful" in the documentation than "not helpful enough". The documentation …
=> Add suggestion to use `--extractor` on MemoryError

aqt/archives.py, aqt/installer.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml, tests/test_cli.py, tests/test_install.py
This is intended to fix #442.
I think that `aqt install-tool` was broken in #414; when I wrote that PR, I expected the Azure Pipeline to test the functionality for me. However, ~~it looks like the Azure Pipeline isn't running `aqt install-tool` or `aqt tool` at all. The conditions necessary to trigger the branch that runs `aqt install-tool` are never present!~~ The Azure Pipeline is running `aqt install-tool` in Powershell, and the command fails, but the error doesn't stop the build. The Pipeline reports success when it should not: https://dev.azure.com/miurahr/github/_build/results?buildId=4670&view=logs&j=9f3e9a58-f4d0-59eb-bb9a-f7c4195515fd&t=ab3feae7-bfd0-56cc-c86f-b7f3a75b7170&l=13
This PR works when tested ad-hoc on my machine.
This PR will be ready to merge after I have implemented …
=> fix broken install-tool

.github/workflows/check.yml
Recently, every "Upload Coverage" step fails for me. This should fix it.
Example of failed "Upload Coverage" step: https://github.com/ddalcino/aqtinstall/runs/4122878621?check_suite_focus=true#step:8:31
=> fix failing coverage upload

azure-pipelines.yml, ci/generate_azure_pipelines_matrices.py, ci/steps.yml
As you can see in a recent Azure Pipelines build, the Windows Server 2016 image is now deprecated: https://dev.azure.com/miurahr/github/_build/results?buildId=4687&view=logs&j=c4497b2b-649a-591e-539b-0d716883e33e
The newer `vmImage: 'windows-2022'` would work too; see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
=> Use `windows-2019` image in CI

aqt/updater.py
Catch IOError or OSError that raised by launching `qmake -query` when cross platform installation.
Fix #449
=> Fix cross-platform installation failure

ci/generate_azure_pipelines_matrices.py
The current CI test for QtIFW assumes that QtIFW will always be version 4.1. The [last run of the Azure Pipeline](https://dev.azure.com/miurahr/github/_build/results?buildId=4735&view=results) demonstrated what happens when the Qt repo updates QtIFW to the next version: The test fails.
This change should make the CI test resilient to version updates, by using a `*` glob instead of a version number.
=> Fix test for QtIFW

azure-pipelines.yml
Azure Pipelines has deprecated macOS-10.14 builds, and it looks like they will remove that OS on December 10, 2021.
This PR updates the macOS build to macOS-10.15.
We could also use `macOS-latest` for this instead; that would ensure that the OS never gets deprecated. 
See: https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
=> Update deprecated MacOS build in CI

aqt/helper.py, aqt/installer.py, aqt/settings.ini, docs/cli.rst, docs/configuration.rst, tests/test_cli.py, tests/test_helper.py, tests/test_install.py
Adds the option `--archive-dest <path>`.
For convenience/readability, this will also turn any reference to the downloaded file in `helper.py` and `installer.py` into a `pathlib.Path` object. This makes it easier to ensure that the file ends up in the right location.
This also adds items in `settings.ini` that control the default behavior of `--keep` and `--archive-dest`.
Fix #421
=> Feature: allow user to specify the download location of 7z archives

setup.cfg
- Resolve symbolic link error (#438)
- Resolve memory error on 32bit python (#436)
=> Bump dependency py7zr@0.17.0

aqt/installer.py, pyproject.toml, setup.cfg
by running `tox -e py39d`
```
================================ leaks summary =================================
tests/test_install.py::test_install[cmd0-linux-desktop-1.2.3-0-197001020304---linux_x64/desktop/tools_qtcreator/Updates.xml-archives0-^aqtinstall\\(aqt\\) v.* on Python 3.*\\nDownloading qt.tools.qtcreator...\\nFinished installation of tools_qtcreator-linux-qt.tools.qtcreator.7z in .*\\nFinished installation\\nTime elapsed: .* second]: leaked references: [42, 43, 44, 45], memory blocks: [16, 16, 16, 16]
tests/test_install.py::test_install[cmd1-linux-desktop-1.2.3---linux_x64/desktop/tools_qtcreator/Updates.xml-archives1-^aqtinstall\\(aqt\\) v.* on Python 3.*\\nWarning: The command 'tool' is deprecated and marked for removal in a future version of aqt.\\nIn the future, please use …
```
=> Reduce memory consumption on 32bit python

azure-pipelines.yml, ci/steps.yml
There are frequent failures in Azure Pipelines builds for Windows, caused by failures to retrieve the the Powershell modules 'Pscx' and 'VSSetup' from the PowerShell Gallery. This PR is intended to cache the Powershell modules required by the Azure pipelines, so that these failures stop occurring. As a side effect, it will also speed up all Windows build jobs by however long it takes to download the powershell modules (expect 1-2 minutes).
Examples of failures:
https://dev.azure.com/miurahr/github/_build/results?buildId=4817&view=logs&j=9f3e9a58-f4d0-59eb-bb9a-f7c4195515fd&t=d65f8022-fa96-505b-389b-6aa2d54135b0&l=27 (from #459)
https://dev.azure.com/miurahr/github/_build/results?buildId=4831&view=logs&j=dcd50a69-7bd8-59f7-72b1-a119e6ffb32f&t=b0305de3-bc12-557b-67f0-1215b8f079d0&l=28 (from …
=> Cache PowerShell Modules in Azure Pipelines

.github/workflows/upload-release-artifacts.yml
Here is a proposition to release a 32 bit binary (there are still computers of less than 5 years old limited to 32 bit Windows, e.g. Intel Compute Stick, ZOTAC Pico, ASUS Transformer). This would probably simplify also the installation of this [Chocolatey package](https://community.chocolatey.org/packages/qt5-default) by removing the Python dependency.
Separate binaries `aqt_x64.exe` and `aqt_x86.exe` are generated, see https://github.com/lebarsfa/aqtinstall/releases. I do not know if the continuous release `aqt.exe` should be in 64 or 32, at the moment it is left to 64 in that code.
=> Add 32 bit binary to release

.github/ISSUE_TEMPLATE/bug_report.md
This removes the redundant request to print the result of `python -VV`. It also fixes the requested `aqt version` request.
Relevant to discussion in #475
=> Fix issue template redundancy

aqt/helper.py, tests/test_helper.py
getUrl() now use `requests.get()` that is default getter that does not retry.
This change corrects it to `session.get()`
Related issue #472
=> Fix behavior that getUrl() does not retry

aqt/archives.py, aqt/installer.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml, docs/cli.rst, docs/getting_started.rst, tests/test_archives.py
This changes the behavior of `--archives` so that it will affect the base module and the debug_info module, but no other modules.
Without this change, the following commands would fail to install the requested modules, and would not generate error messages. This change would allow these command to install the requested modules without a problem.
```bash
aqt install-qt linux desktop 5.15.2 --modules qtcharts --archives qtbase           # did not specify archive `qtcharts`
aqt install-doc linux desktop 6.1.0 --modules qtlottie --archives qtdoc qtlottie   # wrong archive name for qtlottie
```
Fix #457
=> Restrict effect of `--archives` flag to base and debug_info modules

aqt/settings.ini
Some of the currently listed mirrors are no longer part of the official mirror list by qt.io, some return 404, some don't fully mirror the tree (especially `online/`).
The updated list has been generated via the following one-liner:
```bash
for mirror in $(curl -s https://download.qt.io/static/mirrorlist/ | grep -oP 'href="\K(http.*)(?=">HTTP</a>)' | sed -re 's|^http:|https:|; s|([^/])$|\1/|'); do code=$(curl -I "${mirror}online/qtsdkrepository/windows_x86/desktop/qt6_623/qt.qt6.623.win64_msvc2019_64/6.2.3-0-202201260729qtbase-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z" --write-out '%{response_code}' --silent -o /dev/null); [[ $code == 200 ]] && echo "    ${mirror}"; done
```
=> Update fallback mirror list

docs/cli.rst
This adds the `-c | --config` flag to the CLI section of the documentation.
This problem was discovered while investigating #488. It does not attempt to fix that issue.
=> Add explanation of --config flag in CLI docs

ci/steps.yml
The test for `aqt install-tool tools_ifw` recently broke (see https://dev.azure.com/miurahr/github/_build/results?buildId=4989&view=logs&j=bb161906-9c9f-5a9b-90ad-afa0705db589&t=391c2a88-2bdd-5aba-6df6-88fd685f0fd3&l=78) because `archivegen` now requires some x11/libxcb dependencies that it did not require before. This PR adds all of those dependencies so the test will not fail. It does not affect any of the other builds that do not require these dependencies.
=> Fix failing `aqt install-tool tools_ifw` test on Ubuntu

aqt/archives.py, aqt/exceptions.py, aqt/helper.py, aqt/installer.py, aqt/metadata.py, aqt/settings.ini, docs/configuration.rst, tests/test_archives.py, tests/test_cli.py, tests/test_doc_archives.py, tests/test_helper.py, tests/test_install.py, tests/test_list.py
This change causes `aqt` to use SHA-256 checksums for all downloads, and only download them from a list of trusted mirrors. By default, this list includes only https://download.qt.io, but the settings.ini file may be used to modify this list. The settings.ini file can also be used to set the number of times to retry the failed download of a checksum.
Partially addresses #488
Todo:
=> [Security] Use SHA-256 checksums from trusted mirrors only

SECURITY.rst
- 1.2.x as unsupported
- 2.0.x as security fix only
=> Update security policy: bump versions

setup.cfg
- Fix install error for dependency with pip version 61 and later
=> Bump py7zr@0.18.3

pyproject.toml
- set license SPDX compliant name
=> pyproject.toml: change license table to text

aqt/exceptions.py, aqt/metadata.py, tests/test_list.py
Fix #517
This change allows MetadataFactory.iterate_folders to recognize when MetadataFactory has retrieved a malformed HTML file, or an HTML file that does not contain the table and rows that it expects to see.
If the URL is correct, it should retrieve the right page, but this is not guaranteed, and MetadataFactory should be able to recover and generate an appropriate error message.
One possible situation where this kind of error might occur could be when the user is connected to a public WIFI network, but not logged in. The router would redirect aqt to the network login page, and aqt would have no way of knowing that it did not receive the correct page. Aqt should be resilient to this kind of error.
=> Allow MetadataFactory to recover from bad HTML files

aqt/installer.py, aqt/logging.ini, tests/test_cli.py, tests/test_install.py, tests/test_list.py
An enhancement for #529 .
Before:
```console
> aqt install-qt windows desktop 0.0.0 win128
INFO: aqtinstall(aqt) v2.1.1.dev20 on Python 3.8.10 [CPython MSC v.1928 64 bit (AMD64)]
WARNING: Specified Qt version is unknown: 0.0.0.
WARNING: Specified target combination is not valid or unknown: windows desktop win128
ERROR: Failed to locate XML data for Qt version '0.0.0'.
```
After:
```console
> aqt install-qt windows desktop 0.0.0 win128
INFO    : aqtinstall(aqt) v2.1.1.dev21 on Python 3.8.10 [CPython MSC v.1928 64 bit (AMD64)]
WARNING : Specified Qt version is unknown: 0.0.0.
WARNING : Specified target combination is not valid or unknown: windows desktop win128
ERROR   : Failed to locate XML data for Qt version '0.0.0'.
```
Please see commit message for details.
=> Log: left align the level name with padding

pyproject.toml, tests/conftest.py
This PR addresses several warnings I found while trying to debug a failing build in CI:
1. Tox complains about the `entry-points` entry in `pyproject.toml` being dynamic when it is not marked as such. This marks it as dynamic.
2. Pytest complains that one of the custom markers we are using, `load_default_settings`, is not registered. This registers the marker.
3. Pytest complains that 'timeout' is not a valid key in the `pyproject.toml` file. This adds the dependency that provides that key. 
4. Flake8 5.0.0 was released today, and now it is incompatible with flake8-isort. Any attempt to run flake8 results in a failure, because it failed to import flake8-isort properly. This pins flake8 at the highest version below 5.0.0.
Item 4 should probably be reverted after flake8 and flake8-isort …
=> Fix ci warnings/failures

aqt/helper.py, aqt/installer.py, aqt/metadata.py, pyproject.toml, tests/data/windows-5140-expect.json, tests/test_list.py
Fix #543.
#543 suggests 4 new ways to use `aqt list-qt`, but this PR only implements the first of the 4. After implementing this, it is difficult for me to see any point in implementing the other 3, since this command already prints everything you might want to know about a module.
If there's any demand for `aqt list-qt --display-modules`, or for a version of `aqt list-qt --long-modules` that only describes a single module, please let me know and I'll take another look at this. I think that those commands could be convenient for a user that wants to pipe the output into a bash script.
Sample output:
```
$ python -m aqt list-qt linux desktop --long-modules 5.14.0 gcc_64  
Module Name                      Display Name                  Release Date   Download Size   Installed Size …
```
=> Add `aqt list-qt --long-modules`

aqt/exceptions.py, tests/test_list.py
Fix #546. That stack trace shows that keyword arguments are not being passed from ChecksumDownloadFailure to AqtException as intended. This PR adds a test that recreates the conditions that caused #546 and fixes the root cause of the issue.
=> Fix kwargs passed up AqtException inheritance tree

ci/build_standalone.bat, setup.cfg
* update build_standalone.bat to rename pyproject.toml to pyproject.toml.bak to ensure pip installs from setup.cfg
* update dependencies in `setup.cfg`
=> Fix windows standalone binary build

.github/workflows/codeql-analysis.yml
CodeQL Action v1 will be deprecated in December 2022.
See deprecation warnings here: https://github.com/miurahr/aqtinstall/actions/runs/2895457936
See deprecation announcement here: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> Use codeql-action@v2

aqt/installer.py, aqt/metadata.py, aqt/updater.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml, docs/cli.rst, docs/getting_started.rst, tests/test_cli.py, tests/test_install.py, tests/test_list.py, tests/test_updater.py
I think this should fix #528.
* This adds a CLI flag, `--autodesktop`, that automatically installs the required desktop version of Qt if it is not already installed. I chose not to turn it on by default, in order to preserve the existing behavior.
* This adds a warning when `--autodesktop` is not turned on and the expected desktop version of Qt is not present. The warning prints an example command that could be used to install the desktop version of Qt.
Todo:
=> Automatically install desktop qt when required for android/ios qt installations 

README.rst, azure-pipelines.yml, ci/generate_azure_pipelines_matrices.py, docs/cli.rst
The MacOS-10.15 CI runners are now deprecated, and will begin brownouts in August. See discussion here: https://github.com/actions/virtual-environments/issues/5583
~MacOS-11 is also available, in case there are any issues with 12.~ There are issues with 12 so I went to 11.
**Update:** Something's wrong with MacOS-11 too: https://dev.azure.com/miurahr/github/_build/results?buildId=5481&view=logs&j=bae13455-f657-522d-e2b4-64495419fb63&t=5c902093-735e-5ee6-b7c8-ba98a93e04e2&l=58
**Update [2021-09-17]:** I have come to the conclusion that it makes no sense to continue to test using Qt < 6.2.4 with ios, because it is not realistic that it will work. The XCode toolchain has changed significantly in the last few years, breaking compatibility with several things that older versions of Qt relied …
=> Update Mac CI pipelines to use MacOS-12

aqt/archives.py, tests/test_archives.py
Fixes #562. This makes sure that `packageupdate.downloadable_archives` is always an iterable collection of strings, even if that collection is empty, so that aqt does not try to iterate over a `None` object.
=> Tolerate empty DownloadArchive tags while parsing XML

pyproject.toml
- py7zr is updated for security
- avoid traversal path and symlink attack
=> Bump py7zr@0.20.1 [security]

pyproject.toml
flake8-isort 4.2.0 supports flake8 version 5
=> Bump flake8-isort@>=4.2.0

aqt/installer.py
When we print the link with trailing dot, some automatic log-formaters will add that dot to the link itself.
E.g. when you use Github Actions this link will show up with extra dot and therefore does not work.
By removing the dot, the link is functional also in these cases.
=> improve link to report issue

tests/test_cli.py, tests/test_install.py
This fixes two failing tests, as reported here: https://github.com/miurahr/aqtinstall/commit/924e4b087bf509ab62c7d6588dc358d0e31de89e#comments.
=> Fix expected error message in test cases

README.rst, aqt/installer.py, docs/installation.rst, pyproject.toml
It is not mandatory, but we will drop support for python 3.6 in future.
=> Drop support for python 3.6

aqt/updater.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml, tests/test_install.py
This will update `updater.py` so that it patches Qt 6.4.1 for android properly.
Fix #626. Fix #621.
=> Fix patching for Qt 6.4.1 android

aqt/helper.py, aqt/installer.py, ci/settings.ini, tests/test_install.py
- Change Settings class as Borg
- Pass settings values for multiprocessing target function `installer` as arguments
- Avoid loading Settings in `installer` process
- Fix #609
=> Pass settings.ini file path to child process

aqt/archives.py, tests/test_install.py
When a user specifies duplicate modules in an `install-*` command, that command fails (see #632). This change removes all duplicates from the modules list, preventing the error.
Fixes #632.
=> Fix errors in `install-*` caused by duplicate modules

.github/workflows/check-combinations.yml, .github/workflows/check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/release-note.yml, .github/workflows/test-install-qt.yml, .github/workflows/upload-release-artifacts.yml
This fixes some CI warnings about using obsolete versions of NodeJS. NodeJS 12 (from `actions/checkout@2`) is at EOL, and CI warnings recommend using NodeJS 16. The docs for actions/checkout recommend pinning at v3.
Some of these workflows were using `checkout@master`, and were thereby already using NodeJS 16. I'm not sure that it's necessary to use v3 for these instead of master. However, the docs suggest using v3. If at some point the authors decide to rename the `master` branch to `main`, then we may be glad we made this change.
=> Pin checkout at `v3` in all workflows

docs/cli.rst, docs/getting_started.rst
Fix #655
The `win64_mingw` architecture makes it difficult to know which compiler is required. This change explains how to find out (`aqt list-qt windows desktop --long-modules`; the answer is "MinGW 11.2.0").
Additionally, the `tools_mingw90` tool_name and `qt.tools.win64_mingw900` tool_variant are named in a confusing way.  This change explains that they contain MinGW 11.2.0, not 9.0.0.
=> Docs: explain MinGW 11.2.0 and tools_mingw90

aqt/exceptions.py, aqt/installer.py, tests/test_install.py
When the destination drive is not writable or has insufficient space, these exceptions are raised during `run_installer()`. Unless they are caught and dealt with, `aqtinstall` requests that the user file a bug report. This change catches these errors and prints a nice error message instead of requesting a bug report.
Fix #585 and #599. Sorry for jamming these two issues together in the same commit/PR; they seem (loosely) related to me, and it was convenient to address them all at once. If you prefer, I can split this up a bit more.
=> Catch exceptions when destination directory is not writable/insufficient space

aqt/combinations.json, aqt/metadata.py
This allows us to install sdktool using the following command:
aqt install-tool windows desktop sdktool
=> Add support for standalone sdktool installation

aqt/installer.py
Flags must either precede or follow the entire list of positional arguments.
Thanks to @bjorn and #680 for pointing out this issue!
=> Fix help text for list-tool

tests/data/linux-desktop-expect.json, tests/data/linux-desktop.html, tests/data/mac-desktop-expect.json, tests/data/mac-desktop-sdktool-expect.json, tests/data/mac-desktop-sdktool-update.xml, tests/data/mac-desktop.html, tests/data/windows-desktop-expect.json, tests/data/windows-desktop.html, tests/test_install.py, tests/test_list.py
This adds a few tests for the new functionality added in #677.
This probably won't change our code coverage stats much, if at all. However, I am certain that if we don't have these tests, any attempt to refactor existing code in metadata.py or installer.py will break all the functionality added in #677.
=> Add tests for sdktool: install-tool and list-tool

docs/cli.rst
Document command gives:
```
aqt: error: unrecognized arguments: --long-modules tools_mingw90
```
=> Fixed command to check tools_mingw90 version

pyproject.toml
There's a version resolution issue with sphinx and sphinx_rtd_theme; sphinx_rtd_theme just added support for sphinx 7 last week. For some reason, recent docs builds are installing sphinx<2 and sphinx_rtd_theme<0.5, and then installing and running sphinx 7.2.3 and running it with sphinx_rtd_theme 0.4.3.
The version mismatch causes this exception, causing the build to fail:
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/aqtinstall/envs/705/lib/python3.10/site-packages/sphinx/cmd/build.py", line 298, in build_main
app.build(args.force_all, args.filenames)
File "/home/docs/checkouts/readthedocs.org/user_builds/aqtinstall/envs/705/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
self.builder.build_update()
File …
```
=> Fix failing documentation builds

aqt/installer.py, tests/test_install.py
Fix #700.
This is to address a Snyk warning. The new code will only run on Python 3.11.4 and above.
Tested locally with Python 3.11.2 and 3.11.5. Although we can't see it in the code coverage with a single version of Python, I can confirm personally that both arms of the conditional are being entered.
=> Use 'tar' filter when extracting tarfiles

tests/test_install.py
The tarfile test does not permit the new warning, "Extracting may be unsafe; consider updating Python to 3.11.4 or greater". This change should allow the test to succeed when running on 3.11.4 and below.
Failure that would be fixed by this PR: https://github.com/miurahr/aqtinstall/actions/runs/5997958636/workflow
It looks like the failing tests are in test-install-qt.yml, which runs on every push, but I didn't see it before because it isn't linked from the PR page.
=> Fix `test_install` that fails on Python<3.11.4

.readthedocs.yml, aqt/installer.py, aqt/metadata.py, aqt/updater.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml, tests/test_cli.py, tests/test_install.py
Fix #710.
This fixes the behavior of the `--autodesktop` flag and the updater, when installing `win64_msvc2019_arm64` for desktop targets.
This is work in progress for now, because I think it would be worthwhile to add a CI job to the Azure Pipelines that builds a project using this architecture. I haven't quite figured out how to do that yet.
=> Fix installation of win64_msvc2019_arm64 arch

aqt/installer.py, tests/test_cli.py
Inspired by https://github.com/miurahr/aqtinstall/issues/696#issuecomment-1651026317. That comment suggested a place to add a log message, but I was unable to log the message there without disregarding the user’s selected log settings, which are not available until the `Cli` object is built.
When `aqtinstall` fails to load the `py7zr` module, it falls back to whatever 7z extraction tool the user has specified in the `settings.ini` file, without notifying the user. This PR adds the following log message when that happens:
```
WARNING: The py7zr module failed to load. Falling back to '7z' for .7z extraction.
WARNING: You can use the  '--external | -E' flags to select your own extraction tool.
```
This PR also does a little refactoring of the `Cli._set_sevenzip` method to improve …
=> Log a warning when aqtinstall falls back to an external 7z extraction tool

aqt/installer.py, docs/cli.rst
Since #711, the documentation for the `--autodesktop` flag has been a little out-of-date. This PR updates the help text and the explanation in the `cli.rst` file for this flag.
This documentation update probably should have been part of #711, but I forgot to add it.
=> Update documentation for `--autodesktop` flag

.github/workflows/test-install-qt.yml
Fix #712.
This should increase the number of CI jobs run by `test-install-qt.yml` by 18.
Current number of CI jobs: 
* 1 binary build + 3 OSes * 3 Qt versions= 10
New number of CI jobs: 
* 1 binary build + 3 OSes * 3 Qt versions * 3 Python versions = 28
=> Add python 3.8 & 3.11 to `test-install-qt.yml`

.github/workflows/test-install-qt.yml
This does 3 things:
* Add a debug statement to print what aqtinstall commands are being run
* Fix the command that checks which OS to use. See https://github.com/miurahr/aqtinstall/pull/715#issuecomment-1722505571 for explanation of what was broken.
* Run this workflow on pull requests as well as pushes, so we can more easily see when it breaks.
=> Fix failed CI runs in test-install-qt.yml

.readthedocs.yml, docs/conf.py, pyproject.toml
Read the docs service deprecated a configuration `python.system-package` from Aug. 29, 2023.
https://blog.readthedocs.com/drop-support-system-packages/
=> chore: remove deprecated configuration for readthedocs

.github/workflows/upload-release-artifacts.yml
Adds a macOS build to the release artifact upload workflow. This is largely built on the existing job but with some minor tweaks for cross-OS compatibility.
Each target is specified in a matrix with the following properties:
* `os`: Operating system to run on and build for.
* `arch`: Architecture to build for.
* `output_file`: Name of the output executable created by the build.
* `primary_artifact`: Name of the primary artifact executable to create in the release, or blank to not create one.
* This is for uploading `aqt_x64.exe` as `aqt.exe` for Windows and `aqt_x64` as `aqt-macos` for Mac.
* `secondary_artifact`: Name of the secondary artifact executable to create in the release, or blank to not create one.
* This is for uploading the artifact with its full name including architecture. …
=> Add macOS builds to release artifacts.

aqt/archives.py, aqt/helper.py, aqt/installer.py, aqt/metadata.py, aqt/settings.ini, docs/configuration.rst
Based on the work of @mardy and as a quick workaround for some problems described in #521 and #224, here is a proposition to add `ignore_hash` option in `settings.ini`. When set to `True`, `sha256` hashes would not be checked.
=> Add `ignore_hash` option in `settings.ini`

pyproject.toml
- Versions of Requests between v2.3.0 and v2.30.0 are vulnerable to potential forwarding of Proxy-Authorization headers to destination servers when following HTTPS redirects.
Details at [Github Advisory](https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q)
=> security: CVE-2023-32681: bump requests@2.31.0

docs/getting_started.rst
Fixes https://github.com/miurahr/aqtinstall/issues/753
=> Add docs clarifying list-doc and install-doc

aqt/metadata.py, ci/generate_combinations.py
Fix issues discovered in #751. See https://github.com/miurahr/aqtinstall/pull/751#issuecomment-1935347831
Qt 6.7.0 changes the default arch for Linux from gcc_64 to linux_gcc_64. This allows the generate_combinations.py script to account for that.
Also, Qt 6.7.0 is missing a few architectures that were present in earlier versions of Qt6. This makes sure that the script can pick those up.
=> fix generate_combinations issue with Linux Qt 6.7

aqt/metadata.py, ci/generate_combinations.py
I messed up on #756; I thought the CI would run it and catch any errors. It doesn't run properly when I run it locally. This version runs properly.
=> Fix generate combinations

docs/getting_started.rst
Substitute `This exercise is left to the reader` with a particular command. 
Another possibility was:  `$ aqt install-qt windows desktop 5.15.2 win64_mingw81 -m $(aqt list-qt windows desktop --modules 5.15.2 win64_mingw81 | awk '{for (i=1; i<=NF; i++) if ($i != "qtnetworkauth") printf("%s ", $i)}')`
=> Add code to remove qtnetworkauth from a list

.github/workflows/check.yml, .github/workflows/test-install-qt.yml, aqt/archives.py, aqt/combinations.json, aqt/installer.py, aqt/metadata.py, azure-pipelines.yml, ci/generate_azure_pipelines_matrices.py, docs/CHANGELOG.rst, docs/cli.rst, docs/getting_started.rst, tests/data/linux_arm64-desktop-expect.json, tests/data/linux_arm64-desktop.html, tests/test_install.py, tests/test_list.py
Alternative implementation to #765 
Fixes #750
=> Support linux_gcc_arm64 arch in 6.7.0 via new linux_arm64 host

docs/CHANGELOG.rst, docs/installation.rst, pyproject.toml
- Minimum required python version to be 3.8.10, a last version which got regular bug fixes.
- tox: drop 3.7 and add 3.12
- Next aqtinstall release will be version 3.2.0
Note: when merged,  should update `docs/SECURITY.rst` to make 3.0.x unsupported, and 3.1.x to be security fix only.
=> Drop support for Python 3.7

aqt/archives.py, aqt/installer.py, aqt/metadata.py
Fixes https://github.com/miurahr/aqtinstall/issues/775
=> Override host/target for src/docs if Qt >= 6.7.0

aqt/archives.py
This fixes installing Android for 6.7.0 and newer
`list-qt` still doesn't list this version, but I don't know how to approach this one. This PR at least fixes the downloads via `install-qt`
=> Fix installing Qt for Android 6.7.0

aqt/archives.py
=> fix: doc/src/example URL in Qt 6.8.0

azure-pipelines.yml
macOS-12 will be deprecated in Dec 2024.
This change bumps the target to macOS-14
see
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
=> chore(ci): azure-pipelines bump to macos-14

aqt/installer.py, aqt/metadata.py, aqt/updater.py
Fixes the issue [described here](https://github.com/miurahr/aqtinstall/issues/825#issuecomment-2400125218).
I was able to test it via [install-qt-action](https://github.com/jurplel/install-qt-action) by specifying `aqtsource` to point to a tag on my forked aqtinstall repo. I can confirm that it's now working properly as evidenced by the "Install Qt" step in [this build log](https://github.com/jdpurcell/qView/actions/runs/11264500863/job/31324610014).
=> Fix for arch win64_msvc2022_arm64_cross_compiled

.github/workflows/check.yml, .github/workflows/test-install-qt.yml, aqt/installer.py, docs/cli.rst, tests/test_cli.py, tests/test_install.py
- Drop CI test for legacy commands
- Drop test cases for legacy commands
- Drop logics for legacy commands
=> refactor: remove legacy subcommand syntax

aqt/metadata.py, aqt/updater.py, ci/generate_azure_pipelines_matrices.py, ci/steps.yml
=> bug: fix error when instaling win64_llvm_mingw / Qt 6.7 and 6.8

aqt/archives.py, aqt/metadata.py
This allows install-qt to find and install qtwebengine on mac, windows, linux, linux_arm64 with 6.8.0.  It may work with qtpdf as well.
However, list-qt doesn't find qtwebengine.  I suspect there are other deficiencies.
This is related to #803, #818, #824.
I don't expect this PR to be merged as is, but I offer it
- in the spirit of #818 
- in desperation to get CI running with 6.8.0 for https://github/GPSBabel/gpsbabel.git
Note that 6.8.1 is expected to release in a few days.
=> search for modules in extensions directory

aqt/archives.py, aqt/metadata.py
for example with windows desktop 6.8.1 win64_msvc2022_arm64_cross_compiled both qtwebengine and qtpdf don't exist.
this resolves #851
=> handle cases where extensions don't exist.

.github/workflows/codeql-analysis.yml
Addresses:
`CodeQL Action v2 will be deprecated on December 5th, 2024.`
`Please update all occurrences of the CodeQL Action in your workflow files to v3.`
For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
* Bump codeql-action/init to v3
* Bump codeql-action/analyze to v3
=> Update codeql-analysis workflow

.github/workflows/check.yml, .github/workflows/run-linter.yml
Resolve #861 
- Run linter the PR is against master branch
- Run linter when pull-request triggered
- Allow review dog to put review comment on PR
=> chore: give pr permission for reviewdog

tests/test_install.py
This test can be used to reproduce #867 by changing INSECURE_NOT_FOR_PRODUCTION_ignore_hash to True in settings.ini.  It can also be used to verify #868 resolves the issue.
=> enhance test_install to exercise extensions

docs/cli.rst, docs/getting_started.rst
- Update the documentation to showcase more recent versions as examples
- Add examples for versions 6.5.*, 6.6.*
- Add examples and explanations for how to install WASM for Qt 6.7+ (with `all_os` and `wasm`) in preparation for the merge of PR #846
=> Update docs for more recent versions of Qt, and for WASM

.github/workflows/publish-to-pypi.yml
PyPI encourage us to use "Trusted Publishing". This is a part of migration.
=> chore: support trusted publisher to publish with OIDC

ci/generate_azure_pipelines_matrices.py, ci/steps.yml
When the Windows ARM64 job was [initially added](https://github.com/miurahr/aqtinstall/commit/15f72c5c9df77d3c1794c4f96f3bc52769aa7a3f), it attempted to initialize vcvars with `arm64` architecture, but it didn't work and was [reverted](https://github.com/miurahr/aqtinstall/commit/8ad9c686e385af66a6d9d348a8a7f4e3d9b00710) soon after. It was almost correct though, it just needed to be `amd64_arm64` to indicate an [ARM64 on x64 cross](https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#vcvarsall-syntax) compilation.
This PR brings back the vcvars architecture support for ARM64 to fix a compilation error when [updating jom](https://github.com/miurahr/aqtinstall/pull/892). The condition (`'$(ARCH)' -like 'win64_msvc*_arm64*'`) now includes a `*` at the end, …
=> chore(ci): Fix/update Windows ARM64 cross-compilation job

MANIFEST.in, aqt/commercial.py, aqt/helper.py, aqt/installer.py, tests/test_commercial.py, tests/test_helper.py
The current `install-qt-officiial` feature uses requests library directory. 
This PR replace `requests.get` with `aqt.helper.downloadBinaryFile` 
Also, this updates functional test to adopt a method signature change, and to use of tmp_path fixture.
=> feat: install-qt-official checks hash for downloaded binary

aqt/commercial.py, aqt/helper.py, aqt/installer.py, tests/test_commercial.py
Fixes #889. In addition to the incorrect download URL, the file we get is a macOS `.dmg` (disk image) which cannot be executed directly, so this handles mounting/extracting the contents. After these changes, I was able to successfully complete a [macOS build](https://github.com/jdpurcell/QtHelloWorld/actions/runs/13610178522/job/38046297825) via GitHub Actions with the official installer.
=> Fix official installer on macOS

ci/steps.yml
* Use latest jom (1.1.4) for test.
* **md5sum** = `4cd0e6fb721e063b24232bc9ecb6d130`
* https://download.qt.io/official_releases/jom/md5sums.txt
* https://mirrors.ukfast.co.uk/sites/qt.io/official_releases/jom/changelog.txt
* https://download.qt.io/official_releases/jom/?C=N;O=D
=> Use latest jom for test

aqt/updater.py, tests/test_install.py
I thought there was a problem with target_qt.conf patching for WASM recently because I didn't see it in the console output, but it was actually working fine! This function just wasn't writing to the logger like the other patching functions 😄
=> Fix missing log statement for target_qt.conf

aqt/archives.py, aqt/helper.py, aqt/installer.py, aqt/metadata.py
Very simple implementation. Will ignore `host` (as the official installer only lists the packages for your current OS, but the `host` value must still be provided and valid), will use `target` as research term, along with eventual `arch`, using the following regex: `^.*{re.escape(version_str)}\.{re.escape(target_str)}.*$`. Similar to `install-qt`, it will list all the arguments ignored.  
For example, if you use `aqt list-qt linux android --arch 6.8.3 --use-official-installer` on Linux, it will trigger a search using the official installer like this: 
```console
kidev:~$ aqt list-qt all_os android --arch 6.8.3 --use-official-installer 
INFO    : Using official Qt installer for search
INFO    : Downloading Qt installer to /home/kidev/.local/share/aqt/tmp/qt-online-installer-linux-x64-online …
```
=> Fix arch guessing error when version not fully qualified, fix list-qt android, add --UNSAFE-ignore-hash, add --use-official-installer to list-qt

aqt/updater.py
Qt 6.8 has added Windows on Arm as a supported configuration.  The restriction "Windows on ARM is only supported as a deployment target. Applications have to be cross-compiled from an x86-64 Windows machine and deployed to target." has been removed.
This PR simply treats windows and windows_arm64 hosts identically when patching files and creating scripts.  Some of these cases don't actually apply to WoA, but I treated them all identically for consistency.  For example patch_qt_core won't ever do anything on WoA because the windows_arm64 hosts wasn't ever supported with Qt 5.
Note other issues prevent aqt from running on WoA machines, e.g. https://codeberg.org/miurahr/pyppmd/issues/128.  However, this at least allows the WoA install to be done on another machine type and subsequently …
=> update host windows_arm64 files as we do with windows.

docs/CHANGELOG.rst, docs/authors.rst
- Update changelog
- Plan to bump minor version from 3.2.1 to 3.3.0.\
- Also update authors.rst 
- Added @tsteven4 and Alexandre @Kidev Poumaroux's major contributions to the description section.
- Adjusted individual contribution details for multiple authors and updated the alphabetical list accordingly.
=> Update changelog for preparation of the next v3.3.0 release

docs/conf.py
The document linter to ignore problematic link to p7zip project.
=> chore(ci): Update linkcheck_ignore list in documentation configuration

.github/workflows/upload-release-artifacts.yml
Complete #930 
- Add binaries for Windows arm64 and macOS15 arm64
- Make the Github Action script use `windows-2025` instead of `windows-latest` for stability
**[Binaries available for download here](https://github.com/Kidev/aqtinstall/releases/tag/v3.4.0) to test**  
_(build run available [here](https://github.com/Kidev/aqtinstall/actions/runs/16254178111) for details)_
=> Add binaries for windows-arm64 and macos15-arm64
