miurahr/aqtinstall

qli-installer.py

multiprocessing download

---

CHANGELOG.rst
README.rst
aqt/archives.py
aqt/cli.py
aqt/installer.py
docs/cli.rst

Allow user to specify mirror site base url as option -b|--base
Close(#24)

mirror selection option(#24)

---

.travis.yml
CHANGELOG.rst
README.rst
aqt/cli.py
aqt/installer.py
requirements.txt
setup.py

Use py7zr for extracting package 7z archive

---

.travis.yml
README.rst
aqt/cli.py
ci/steps.yml
requirements.txt

Switch default to use external 7zip command to extract package

---

CHANGELOG.rst
README.rst
aqt/archives.py
aqt/cli.py
aqt/installer.py
ci/steps.yml

Support Tools installation

---

aqt/archives.py
aqt/installer.py
azure-pipelines.yml
ci/generate_azure_pipelines_matrices.py
ci/steps.yml

- Add CI test for tool installation 
- Fix syntax error and refactoring

Add CI test for tool installation

---

CHANGELOG.rst
aqt/installer.py
ci/steps.yml

Change install path (#48)

---

aqt/installer.py

update qconfig.pri licheck

---

aqt/cli.py
requirements.txt

Do not exist when combination check fails but warning

---

azure-pipelines.yml
ci/generate_azure_pipelines_matrices.py
ci/steps.yml

Fix broken link and ask to install latest with fastcomp backend

CI: update wasm emsdk version

---

ci/generate_azure_pipelines_matrices.py
requirements.txt
setup.cfg

- This reduce a problem of  issue #86.

Limit py7zr version to 0.5.*

---

.travis.yml
aqt/archives.py
aqt/cli.py
aqt/combinations.json
aqt/installer.py
aqt/settings.py
requirements.txt
setup.cfg
tests/test_cli.py
tests/test_connection.py
tox.ini

- CLI: check version number existence and print warning if unknown
- Improve error messages and handling
- Closes #93

Check version number and improve error messages

---

aqt/cli.py
docs/internals.rst
requirements.txt
setup.cfg

When launching command, print aqtinstall version and running platform.
Implement #103

Print aqt version at first line

---

aqt/helper.py
aqt/installer.py

Check redirect location before getting metalink data

---

README.rst

README: Add github actions badge

---

aqt/cli.py
tests/test_connection.py

CLI: Change version info and test excpectation

---

aqt/installer.py
tests/test_helper.py

Limit retries with back-off factor

---

MANIFEST.in
ci/settings.ini
ci/steps.yml

Azure: insert random sleep to reduce server load

---

aqt/installer.py

- Use multiprocessing.dummy.Pool()
- Related issue #98

Revert a part of #87 modification(Relelase v0.7.*)

---

.github/workflows/test-install-qt.yml
aqt/archives.py
aqt/cli.py
aqt/combinations.json
azure-pipelines.yml
ci/generate_azure_pipelines_matrices.py
ci/steps.yml
tests/test_archives.py
tox.ini

Fix handling of QtArchive variables

---

ci/steps.yml

AP: test --outputdir option

---

aqt/archives.py
azure-pipelines.yml
ci/generate_azure_pipelines_matrices.py
ci/steps.yml

AP: add build test with mingw

---

README.rst

Add clause to express aqtinstall's policy not to touch environment variables such as PATH.
Related #100

README: express about environment variable policy

---

CHANGELOG.rst
aqt/archives.py
aqt/cli.py
aqt/installer.py
azure-pipelines.yml
ci/steps.yml

CLI: Introduce --archives option

---

.github/workflows/test-install-qt.yml
CHANGELOG.rst
aqt/archives.py
aqt/combinations.json
aqt/helper.py
aqt/installer.py
aqt/qtpatch.py
ci/generate_azure_pipelines_matrices.py

- Patch qmake hard coded path with installed prefix(#100)

Patch qmake as finalize process

---

aqt/cli.py
tests/test_cli.py

Show help when launched without any argument

---

CHANGELOG.rst
README.rst
aqt/archives.py
aqt/cli.py
aqt/installer.py
azure-pipelines.yml
ci/steps.yml
docs/cli.rst
tests/test_cli.py

Add subcommand to install doc src and examples

---

docs/internals.rst

Update internal auto document

---

aqt/archives.py
aqt/cli.py

Do not raise exception for unknown combinations

---

CHANGELOG.rst
aqt/archives.py
aqt/combinations.json

Support for Qt6

---

aqt/cli.py

cli: set show_help as default

---

.github/workflows/test-install-qt.yml

GHA: add test case with Qt5.7

---

aqt/installer.py

Fix to catch extraction error

---

aqt/archives.py

Fixes for #153  posted by  @MasterQ32

Check whether download archives is None

---

aqt/archives.py
aqt/cli.py
setup.cfg
tox.ini

Add list command

---

README.rst

Can you add an example for the `--archives` option? It's not clear to me how to use it.

Fix typos and install usage in README

---

README.rst

fix #170
I have updated the old broken example in the readme file.

Update tools_ifw example

---

aqt/cli.py
aqt/installer.py

Utilize multiprocessing for better performance.

Utilize multiprocessing

---

README.rst
aqt/archives.py
aqt/installer.py
tests/test_archives.py
tests/test_doc_archives.py

Add feature to select fallback mirror site randomly from known sites.
ref #194

Select fallback mirror site when main site connection failed

---

README.rst
aqt/archives.py
aqt/installer.py

- set timeout for requests connections. default: 5.0 seconds.
- Introduce `--timeout` CLI option.
- workaround for #197

Add --timeout option for connection

---

aqt/archives.py
aqt/installer.py

Update list command to work for Qt6

---

aqt/helper.py
aqt/installer.py
aqt/updater.py
ci/steps.yml

- Patch pkgconfig configurations
- Patch libQt5Core and libQt6Core for linux
- Catch exception on qmake -query execution
- Implemnted #199

Improve patching

---

aqt/installer.py
docs/cli.rst

- Implement #174
- Introduce --noarchives option

Support Adding modules to existing install

---

ci/steps.yml

Change jom download mirror to avoid error

---

aqt/archives.py
aqt/installer.py

Enhance fallback mechanism with timeout error(#215)

Catch timeout connection then fallback

---

MANIFEST.in
aqt/archives.py
aqt/cuteci.py
aqt/install-qt.qs
aqt/installer.py
setup.cfg
tests/test_archives.py
tests/test_cli.py

Integrate cuteci installer into aqtinstall

---

.github/workflows/test-install-qt.yml
aqt/archives.py
aqt/cuteci.py
aqt/exceptions.py
aqt/helper.py
aqt/installer.py
ci/settings.ini
ci/steps.yml

- Check black list for all network connections
- Move network code into helpers.py
- Move exceptions in exceptions.py
- CI: Github actions see custom settings.ini

Refactoring network code

---

aqt/helper.py
aqt/installer.py
aqt/settings.ini
ci/generate_azure_pipelines_matrices.py
ci/settings.ini
ci/steps.yml
docs/configuration.rst
docs/index.rst
tests/data/settings.ini
tests/test_archives.py
tests/test_cli.py
tests/test_doc_archives.py

- Move more constants into settings.ini
- Introduce -c/--config CONFIG command line option
- Multi-line URL for blacklist configuration 
- Azure: use -c option to pass custom configuration
- Azure: windows: use -b option to avoid error

Improve settings.ini configuration handlings

---

.github/workflows/check.yml
MANIFEST.in
aqt/cuteci.py
aqt/helper.py
aqt/installer.py
tests/conftest.py
tests/test_archives.py

This reverts commit d16c9e1bcf54b991cef312db937bb93aba7f22db. and  25d63bf.
Supersede #247

Revert "Attempt to get tox to run in GH Actions"

---

setup.cfg
tox.ini

Check isort with flake8-isort plugin

tox: improve check with flake8 plugins

---

aqt/updater.py

I think this is the fix for #256.  Be aware I am unfamiliar with any test process you may have, and I do not regularly program in python.

fix binfile patching.

---

.github/workflows/test-install-qt.yml
.gitignore
MANIFEST.in
aqt/__init__.py
aqt/installer.py
pyproject.toml
setup.cfg
setup.py
tests/test_cli.py

- Set aqt version by version.py generation
- Drop importlib and pkg_resources chunks of code
- Fixed #261

Version subcommand

---

ci/steps.yml

CI: random sleep < 60s

---

aqt/updater.py

patch pkgconfig files on mac, libtool control files on linux and mac

---

aqt/archives.py

Fix function error when migrating semantic_version package
fix #275

Fix version comparison (#275)

---

aqt/updater.py

create qtenv2.bat file on windows

---

aqt/archives.py

Fix wrong base path in run_list

---

aqt/archives.py

Thanks @ddalcino for catching it on https://github.com/miurahr/aqtinstall/pull/281#discussion_r660887456

Hotfix #281

---

aqt/helper.py

This PR fixes several different issues in `helper.getUrl`. Please see the individual commit messages for details and the reasoning behind each change.
If you'd like, I can split this into four separate PRs, because this change fixes four separate problems. I just thought it would be easier to handle them all at once, since they're all in the same function.

Fix issues in getUrl

---

tests/test_connection.py

Sorry, when I changed the error message in #292, I forgot to change the corresponding test code that checks it!

Fix test_connection.py (again ... oops)

---

aqt/installer.py

Change log level to debug for settings.ini loading

---

.github/workflows/publish-to-test-pypi.yml

GHA: fix release condition

---

aqt/updater.py

Fix update path for winrt

---

aqt/archives.py
aqt/installer.py
setup.cfg
tests/test_archives.py
tests/test_doc_archives.py

Utilize dataclasses

---

.github/workflows/check.yml
README.rst
pyproject.toml
tox.ini

Add coverage test

---

aqt/archives.py

Drop unused class

---

aqt/archives.py
aqt/installer.py

- Introduce `run_installer` that consume `List[QtArchives]` data
spin-off from #309

Refactoring call_instaler/installer

---

aqt/metadata.py
tests/test_list.py

List of tools with adaptive terminal width

---

docs/cli.rst

Use doscon for windows command example

docs: Update command example lexer

---

README.rst

Link documentation for stable

---

aqt/installer.py

Gracefully terminate when keyboard interrupt

---

SECURITY.rst

Update security policy

---

ci/generate_combinations.py

Fix #342. This problem was related to refactoring the List subcommand, which changed the ArchiveId.category to receive "qt" or "tools", instead of "qt5", "qt6", or "tools".

Fix generate combos

---

README.rst

This is intended to prevent issues like #347.

Recommend running aqt with python3 on old systems

---

aqt/__main__.py

Check python version before start.

---

aqt/archives.py
aqt/helper.py
aqt/installer.py
aqt/metadata.py
aqt/updater.py
pyproject.toml
setup.cfg
tests/test_archives.py
tests/test_cli.py
tests/test_doc_archives.py
tests/test_helper.py
tests/test_list.py
tox.ini

- move config from tox.ini to pyproject.toml
- because flake8 does not support pyproject.toml so
setup.cfg is the live configuration.

Update lint config

---

aqt/archives.py
aqt/updater.py
ci/generate_azure_pipelines_matrices.py

In https://github.com/miurahr/aqtinstall/issues/363#issuecomment-897710963, @jurplel requested a new release with #364 applied. This PR is my attempt to backport this fix to the stable branch. I am not sure when version 2.0 will be ready for release, but if that's not going to happen soon, I think we should continue to support v1.2.
I am happy to close this PR if version 2.0 is ready to release.

Apply #364 to stable

---

.github/workflows/check.yml
aqt/__init__.py
aqt/__main__.py

Fix version check

---

CHANGELOG.rst

The master branch does not have changelog entries for releases 1.2.3 to 1.2.5. This PR adds these entries to the master branch.

Add new changelog entries for stable branch

---

.github/workflows/upload-release-artifacts.yml
README.rst

This PR explains where to find aqt.exe, and why you might want it, as requested in https://github.com/miurahr/aqtinstall/pull/393#issuecomment-920968615

Add documentation for aqt.exe

---

.github/workflows/upload-release-artifacts.yml

Ref https://github.com/miurahr/aqtinstall/discussions/404#discussioncomment-1385295 .
Keys:
- [marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20 (latest)](https://github.com/marvinpinto/action-automatic-releases/tree/4edd7a5aabb1bc62e6dc99b3302d587bf3134e20)
- [`core.error()`](https://github.com/actions/toolkit/blob/ea81280a4d48fb0308d40f8f12ae00d117f8acb9/packages/core/README.md#logging) at [uploadReleaseArtifacts.ts#L17](https://github.com/marvinpinto/actions/blob/05a5fd79e119b74bf8fa909a7ecb52bef9aaf1da/packages/automatic-releases/src/uploadReleaseArtifacts.ts#L17)
- [svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2 (2.2.1; v2)](https://github.com/svenstaro/upload-release-action/tree/483c1e56f95e88835747b1c7c60581215016cbf2)
- …

CI (GitHub Actions): use an action that fails when no file is found

---

.github/workflows/test-install-qt.yml

CI: only one job for binary distribution upload

---

aqt/installer.py

Print working dir and aqt version in error msg

---

aqt/archives.py
aqt/helper.py
tests/data/mac-desktop-tools_qtdesignstudio-expect.json
tests/data/mac-desktop-tools_qtdesignstudio-update.xml
tests/test_archives.py

Accept Update.xml that use comma without space as delimiter

---

README.rst

Update README: warning against unrelated aqt

---

aqt/archives.py
aqt/helper.py
aqt/metadata.py
ci/generate_azure_pipelines_matrices.py
ci/generate_combinations.py
setup.cfg
tests/test_install.py

This is an attempt to fix as many easily correctable issues discovered by sonatype as possible.

Fix sonatype issues

---

pyproject.toml
setup.cfg
setup.py

setuptools_scm configuration on pyproject.toml

---

aqt/updater.py
ci/generate_azure_pipelines_matrices.py
ci/steps.yml
tests/test_install.py

Fix #503.
~Disregard for now; I just want to see 2 new tests that fail.~ This adds tests and fixes that allow the tests to pass.

Fix patching of Qt6.2.2-ios

---

README.rst
ci/build_standalone.bat
pyproject.toml
setup.cfg

Support pyproject.toml:project section

---

pyproject.toml

pyproject.toml: add mypy and pytest config

---

docs/conf.py
pyproject.toml

- Update sphinx to 5.0
- Update configurations
- fix language
- extlinks

Bump Sphinx@5.0 and fix related issues

---

README.rst

readme list-qt fix

---

.flake8
MANIFEST.in
pyproject.toml
setup.cfg
setup.py

- Remove setup.py's metadata configuration
- Split flake8 section into .flake8

Deprecate setup.py metadata configuration

---

aqt/archives.py
tests/test_archives.py
tests/test_doc_archives.py

archives: do not keep update.xml text in field

---

aqt/archives.py
tests/data/windows-620-android-armv7-update.xml
tests/data/windows-desktop-tools-mingw-updates.xml
tests/data/windows-desktop-tools-qtcreator-updates.xml
tests/test_archives.py

1. Introduce Updates.xml data class and parser
- PackageUpdate data class to hold a packageupdate section of Updates.xml 
- Updates data class to hold Updates.xml data
2. Use Updates class to handle Updates.xml in archvies package

Introduce Updates.xml data class and parser

---

aqt/installer.py
aqt/metadata.py
tests/test_install.py
tests/test_list.py

This fixes an issue that I had noticed and promptly forgot about: https://github.com/miurahr/aqtinstall/issues/519#issuecomment-1109875714
> After a brief review of the code, it looks like the list-* commands are not capable of setting the base url via CLI argument. This has consequences: at least one install-tool command allows setting base url via CLI argument, and calls MetadataFactory functions, which do not respect the chosen base url. This will need to be fixed.
Before this change, any time `aqt install-qt` or `aqt install-tool` used `MetadataFactory` to resolve a Qt version spec or fetch a list of tools, it would ignore whatever mirror base url the user sets with the `--base` flag and use `Settings.baseurl` instead. This PR fixes that.
Note: There's a big ugly addition to …

Make MetadataFactory respect baseurl set in arguments

---

docs/cli.rst
docs/getting_started.rst

I forgot to include this in #547

Add documentation for the new `--long-modules` flag

---

ci/build_standalone.bat

- Try to fix #564
- set gravitybee variables in environment variables

StandAlone build: set gravitybee variables as environment variables

---

MANIFEST.in

MANIFEST.in: clean list

---

.github/workflows/check.yml
azure-pipelines.yml
ci/generate_azure_pipelines_matrices.py
pyproject.toml

CI: bump target python version to 3.9

---

CHANGELOG.rst
README.rst
docs/authors.rst
docs/cli.rst

- Add --autodesktop example on README
- Update patch version in examples
- Add missing changes

Update documents for release 3.0.0

---

.github/workflows/upload-release-artifacts.yml
ci/build_standalone.py

Actions: fix upload artifact script

---

pyproject.toml
setup.cfg

All build configurations on pyproject.toml

---

.github/workflows/check.yml
.github/workflows/publish-to-pypi.yml
.github/workflows/test-install-qt.yml
aqt/archives.py
aqt/exceptions.py
aqt/helper.py
aqt/installer.py
aqt/metadata.py
aqt/updater.py
ci/generate_combinations.py
pyproject.toml
tests/test_archives.py
tests/test_helper.py
tests/test_install.py
tests/test_list.py

Re-create commit history based on #617  for merge.

Add typecheck and fix errors

---

pyproject.toml

tox 4 accept comma separate value or array for pass_env, and raise error for space separate values

Update tox.ini config

---

ci/generate_azure_pipelines_matrices.py
ci/steps.yml
tests/test_cli.py
tests/test_connection.py
tests/test_helper.py

Also fix test that fails at the moment

Pin EMSDK version for build where useful

---

aqt/installer.py
docs/cli.rst
docs/getting_started.rst

Fix #637.
~Please note that this pulls in two commits from #634, otherwise the tests will not pass.~ **Edit:** rebased onto master

Fix docs qt6 wasm mobile

---

aqt/installer.py
tests/test_cli.py
tests/test_install.py

Improve combination warnings

---

aqt/installer.py
ci/generate_azure_pipelines_matrices.py
tests/test_install.py

Fix #662
I'm pretty sure this is all that needs to happen. I'm not too concerned about the need for unit tests for this, but I can add them if desired.

Fix failed .tar.gz extraction in `install-src` and `install-doc`

---

docs/configuration.rst

Hello!
---
I tried "```sphinx-intl update -l ja```" after editing the docs, but git-diff told me that the changes are a lot and not just the lines I changed, so I didn't commit them in this PR.

Docs: might be unhappy with the default blacklist settings

---

pyproject.toml

- Bump py7zr@0.20.6 it includes the fix: allow specify target path in relative path
- fix #701

fix: exception when target path is relative

---

pyproject.toml

- bump pytest-remotedata@0.4.1
- move pytest-leaks as debug extra
- set extras with debug for py39d,mprof,fil debug/profile configuration of tox

chore(test): introduce debug extras

---

pyproject.toml

- flake8@6.0.0 and later
- flake8-isort@6.0.0 and later

chore: Bump flake8,flake8-isort

---

docs/authors.rst
docs/configuration.rst
docs/getting_started.rst
docs/previous_changes.rst

- add new contributors: thanks Alberto, steveice10 and lebarsfa
- Fix quote words with double backquotes

docs: update authors and fix syntax

---

.git_archival.txt
.gitattributes
MANIFEST.in

- Add .git_archival.txt template that substitute on export

chore: support build on git export

---

aqt/metadata.py

Make base_url argument optional with default to None and replace it with Settings.baseurl if it is None (standard optional argument procedure)

Fix issue #731

---

.github/workflows/test-install-qt.yml
azure-pipelines.yml
ci/generate_azure_pipelines_matrices.py

- Full tests weekly on master
-  mac, windows and linux
- Qt 5.12.12, 5.15.14, 6.5.3
- Python 3.9, 3.10, 3.11 and 3.12
- check sample app built  
- Change trigger for GitHub actions
- mac, windows and linux
- Python 3.9 and 3.12
- Qt 5.9.9, 6.1.0
- check qmake works

chore: update CI execution trigger/schedule

---

aqt/archives.py
aqt/installer.py
aqt/metadata.py
docs/cli.rst

test command line
install:
```
aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 and aqt install-qt windows desktop 6.8.0 win64_mingw
```
list
```
aqt list-qt (windows|mac|linux) desktop --arch 6.8.0
```
try to fix #796

feat: support list and install Qt 6.8.0

---

aqt/archives.py

It modified a URL path of  android distribution for Qt 6.8.0 and later.

fix: installation of android for Qt 6.8.0

---

aqt/installer.py

fix: remove logic to check or warn about unknown combinations

---

.github/workflows/test-install-qt.yml
README.rst
azure-pipelines.yml
pyproject.toml

- ~~Update CI to test with python 3.12 basically~~
- ~~Update CI to drop old Qt versions and add Qt 6 versions~~
- change meta data

chore: drop python 3.8 and add python 3.13

---

.github/workflows/test-install-qt.yml
aqt/archives.py
aqt/installer.py
tests/test_install.py

handle Updates.xml Operation extract elements.

---

aqt/archives.py

This, together with #852, resolves #848.

fix computation of archive location for android install.

---

.github/workflows/run-linter.yml
pyproject.toml

chore: add pylint configration on pyproject.toml

---

MANIFEST.in
aqt/archives.py
aqt/exceptions.py
aqt/helper.py

- exclude .reviewdog.yml from source distribution
- Add more type hints
- protective check for self.config in SettingsClass

Improve type definitions and styles

---

aqt/updater.py
pyproject.toml

chore: migrate to patch_ng

---

ci/steps.yml

- Currently md5sum failed with unknown md5sum file error
- Uses pwsh syntax to check md5 hash

chore(ci): fix jom md5 check

---

docs/commercial.rst
docs/index.rst
docs/official.rst

First documentation draft for the commercial feature. Will keep the docs synced with #883, so do not merge #886 before #883

Commercial docs
